### ISSUE TITLE
Add invitees to Sessions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mofo-allhands#10]
@mmmavis – let's discuss different options for listing session invitees. 
- could we use facilitator 1 & facilitator 2 to list required and optional attendees? 
- would it be crazy to list names as tags? then you could view all your sessions?
- fallback: we drop names into the descriptions

Maybe we can a couple of each option and see how it feels in the app before we commit. 

cc @ldecoursy

**Comment by mmmavis** [comment]
Hey @xmatthewx 

Meant to mention this before I went on PTO - before we make any event-specific/bespoke changes,  I think we should probably save a local copy of `schedule.js` to the [`mofo-allhands`](https://github.com/mozilla/mofo-allhands) repo instead of hotlinking the one on [`schedule-app-core`](https://github.com/mozilla/schedule-app-core).

My preference would be mentioning names in descriptions and people can use the search function to search for names. This way we can avoid making bespoke changes. 😃 

However, if we want to list invitees as separate meta (vs embedded in description) I would suggest _adding_ 2 new fields - one for required attendees and one for optional attendees - instead of altering `facilitator`.

**Comment by xmatthewx** [comment]
Attendee names in Description + Search works for me. Using tags shouldn't require anything bespoke –– would it?

**Comment by mmmavis** [comment]
> Using tags shouldn't require anything bespoke –– would it?

Nope. I'm just worried once the tag list gets long it won't be as useful for people. :laughing:

**Comment by xmatthewx** [comment]
tracking in #9
